name: Create Release

on:
  push:
    tags:
      - 'v*'
# on:
#   release:
#     types: [published]

jobs:
  build:
    # name: Create Release
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@master

    #   - name: Create Release for Tag
    #     id: release_tag
    #     uses: yyx990803/release-tag@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     with:
    #       tag_name: ${{ github.ref }}

      - name: Publish to NPM
        run: npm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - uses: JS-DevTools/npm-publish@v2
  #       with:
  #         token: ${{ secrets.NPM_TOKEN }}

